### ISSUE TITLE
Exception: Cannot find path 'C:\Users\"my_user_name"\AppData\Local\Microsoft\Edge\User Data\Default\Cookies' because it does not exist.Bug report

### ISSUE THREAD

**Issue by LuigiVessella** [techthoughts2/ApertaCookie#4]
### Steps to Reproduce

1.Import-Module -Name "ApertaCookie"
2.$session = Get-DecryptedCookiesInfo -Browser Edge -WebSession -Domain zalando
3.
4.

### Context (Environment)
* Operating System and version as reported by `$PSVersionTable.OS`: Windows 11
* PowerShell versions as reported by `$PSVersionTable.PSEdition`: 7.2.1

### Detailed Description
It shows this error with every browser i try. I manually checked if Cookies file exists and it is but the script return the error in the title.

**Comment by techthoughts2** [comment]
The path is indeed different for Windows 11:

```
# new Windows 11 path:
$env:LOCALAPPDATA\Microsoft\Windows\INetCookies
```

Unfortunately, the cookie file in that location only contains the following entry:

```
Cookies are no longer stored in files.  Please use Internet*Cookie* APIs to access cookies.
```

This will require additional investigation as it appears Edge has gone in a very different direction with cookie management.

**Comment by techthoughts2** [comment]
Closing due to project being archived.
